[package]
name = "bk-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-iterator = "2.3.0"
hex = "0.4.3"
rand = "0.10.1"
rayon = "1.12.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.228"
sha2 = "0.11.0"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = "0.7.18"
uuid = { version = "1.24.0", features = ["v4"] }
wincode = { version = "0.5.4", features = ["derive"] }
